# Generated by Django 4.2.3 on 2023-07-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.TextField(default=None, max_length=45),
        ),
    ]
