# Generated by Django 4.2.3 on 2023-07-31 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='likes',
        ),
    ]
